name: Product-Catalog
on: 
  push: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut-Code
        uses: actions/checkout@v4

      - name: Java-Installation
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: mvn clean package

  

  