name: Product-Catalog
on: 
  push: 
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: CheckOut-Code
        uses: actions/checkout@v4

      - name: Java-Installation
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=product-catalog-api -Dsonar.projectName=product-catalog-api

  

  